# Site settings
title: Simon Prickett's Technical Blog
email: simon@crudworks.org
description: > # this means to ignore newlines until "baseurl:"
  Personal technical blog of Simon Prickett, Architect, mobile subject 
  matter expert and general tinkerer.  Covers PhoneGap / Cordova, 
  Sencha Touch, JQuery Mobile as well as Python and anything else I 
  am playing with.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://simonprickett.github.io" # the base hostname & protocol for your site
twitter_username: simon_prickett
github_username:  simonprickett

# Build settings
markdown: kramdown
timezone: America/Los_Angeles

theme: jekyll-theme-cayman
